import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Image from 'next/image';
import { Container } from "@/components/ui/container";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex min-h-screen flex-col`}
      >
        <header>
          <Container>
            <Image src={"/logo.svg"} width={150} height={86} alt={"Логотип Box Bunny."} />
          </Container>
        </header>
        <main className="flex-1">
          {children}
        </main>
        <footer>
          <Container className="text-center">
            A meal prep app.
          </Container>
        </footer>
      </body>
      
    </html>
  );
}
